#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (! file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
    fwrite(STDERR, "Vendor folder pawa jai nai. Please run: composer install\n");
    exit(1);
}

require $autoload;

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput());

exit($status);